[build.environment]
  NODE_VERSION = "20"
  CLOUDINARY_BASE_URL = "https://res.cloudinary.com/du6xl727e/image/upload"
  NETLIFY_ENV_CLOUDINARY_API_KEY = "_LAI3fKbumFxgclHTtbAuC-0_co"

[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-visual-editor"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173

[visual_editor]
  devCommand = "npm run dev"
  previewPort = 5173
