[build.environment]
  NODE_VERSION = "20"
  CLOUDINARY_BASE_URL = "https://res.cloudinary.com/du6xl727e/image/upload"
  NETLIFY_ENV_CLOUDINARY_API_KEY = "_LAI3fKbumFxgclHTtbAuC-0_co"

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# allow content and assets to resolve normally
[[redirects]]
  from = "/content/*"
  to = "/content/:splat"
  status = 200

# SPA fallback: rewrite only unknown routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
