[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  framework = "vite"
  targetPort = 5173

[visual_editor]
  # The Visual Editor proxies to the Vite dev server so editors see hot updates.
  devCommand = "npm run dev"
  previewPort = 5173
