[build.environment]
  NODE_VERSION = "20"

[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-visual-editor"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173

[visual_editor]
  devCommand = "npm run dev"
  previewPort = 5173

[[headers]]
  for = "/_static/app-assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://create.netlify.com"
    Access-Control-Allow-Credentials = "true"

[[headers]]
  for = "/content/uploads/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://create.netlify.com"
    Access-Control-Allow-Credentials = "true"
